FROM node:15.12.0-alpine

RUN apk --no-cache add curl g++ gcc libgcc libstdc++ linux-headers make python

RUN curl -o- -L https://yarnpkg.com/install.sh | sh

WORKDIR /app

COPY . .

RUN yarn --frozen-lockfile